### PR TITLE
Support for php-parser 5

### PR DESCRIPTION
**Pull request by jasonvarga**
This PR adds support for `nikic/php-parser` 5.0.
It removes support for 4.0.

This has become necessary as PHPUnit 11 requires 5.0. [PHPUnit 11 is now the default in Laravel](https://github.com/laravel/laravel/blob/b3df041d860233e3d1cd325fea41abe6564e894c/composer.json#L18).

### CODE REVIEW

**Comment by ajthinking** [comment]
Hi Jason, thanks for this!
Can you see what is failing here?
image

**Comment by jasonvarga** [comment]
I'm not sure about that one. It fails during setup of the image. It's not a PHPUnit failure.

**Comment by jasonvarga** [comment]
It's because the `composer` command can't be found in that macos image.

CleanShot 2024-05-10 at 16 58 33

Then in the "cache dependencies" step, there is no `path` because it didnt get defined in the previous step.

As for why it's missing. I have no idea. It seems like it's not included with macos. [Maybe it was at some point.](https://github.com/actions/runner-images/pull/9249/files)

This failing step has nothing to do with this PR though. I would compare with previous workflow runs but there don't appear to be any. I have pushed an empty commit to the master branch on my fork to trigger the actions. [You can see it failing there too.](https://github.com/jasonvarga/archetype/actions/runs/9038082634/job/24838475718)

**Comment by ajthinking** [comment]
Found a way! Happy to see youre still using this package❤️ 
Releasing 2.0.0 shortly as this will be a breaking change.

**Comment by ajthinking** [comment]
https://github.com/ajthinking/archetype/releases/tag/v2.0.0

Let me know if it needs any tweeking 👍

**Comment by jasonvarga** [comment]
Thank you!

**Pull request merged**
